insert into infraccion(codigo, descripcion, calificacion, monto) values('I000', 'Infraccion por manejar borracho', 'Muy grave', 1500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I001', 'Infraccion por atropellar', 'Grave', 2000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I002', 'Infraccion por pasarse un semaforo', 'Leve', 2500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I003', 'Infraccion por romper una pared', 'Muy leve', 3000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I004', 'Infraccion por ir a mucha velocidad', 'Leve', 3500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I005', 'Infraccion por matar a un perro', 'Muy leve', 4000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I006', 'Infraccion por subirse en la vereda', 'Grave', 4500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I007', 'Infraccion por manejar sin licencia', 'Muy grave', 1500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I008', 'Infraccion por hacer servicio de taxi sin soat', 'Muy grave', 5000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I009', 'Infraccion por matar una ancianita', 'Muy grave', 5500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I010', 'Infraccion por manejar borracho', 'Muy grave', 1500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I011', 'Infraccion por atropellar', 'Grave', 2000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I012', 'Infraccion por pasarse un semaforo', 'Leve', 2500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I013', 'Infraccion por romper una pared', 'Muy leve', 3000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I014', 'Infraccion por ir a mucha velocidad', 'Leve', 3500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I015', 'Infraccion por matar a un perro', 'Muy leve', 4000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I016', 'Infraccion por subirse en la vereda', 'Grave', 4500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I017', 'Infraccion por manejar sin licencia', 'Muy grave', 1500);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I018', 'Infraccion por hacer servicio de taxi sin soat', 'Muy grave', 5000);
insert into infraccion(codigo, descripcion, calificacion, monto) values('I019', 'Infraccion por matar una ancianita', 'Muy grave', 5500);